### ISSUE TITLE
Chapter01/bike_sharing.py

### ISSUE THREAD

**Issue by BenQuigley** [PacktPublishing/Python-Machine-Learning-Cookbook#2]
In Chapter01/bike_sharing.py, I am getting the following error:

```
$ python bike_sharing.py bike_day.csv
Traceback (most recent call last):
  File "bike_sharing.py", line 39, in <module>
    rf_regressor.fit(X_train, y_train)
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/ensemble/forest.py", line 326, in fit
    for i, t in enumerate(trees))
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/ensemble/forest.py", line 120, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/tree/tree.py", line 1029, in fit
    X_idx_sorted=X_idx_sorted)
  File "/home/BenQuigley/local_projects/machine_learning/venv/local/lib/python2.7/site-packages/sklearn/tree/tree.py", line 199, in fit
    % self.min_samples_split)
ValueError: min_samples_split must be at least 2 or in (0, 1], got 1
```
This comes from line 37 in bike_sharing.py: 

`    rf_regressor = RandomForestRegressor(n_estimators=1000, max_depth=10, min_samples_split=1)
`

Deleting the `min_samples_split` argument lets sklearn default it to 2, which fixes the bug. 1 is not a valid min_samples_split arg per [this issue](https://github.com/scikit-learn/scikit-learn/issues/8041) in the sklearn repo.

**Comment by petertsengruihon** [comment]
thank you. It worked!

**Comment by techsachinkumar** [comment]
Solution provided

Closed.
